### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by chadrobertson75** [mjeanroy/bower-npm-resolver#9] opened 2016-08-04 21:43 UTC
I have just recently implemented Bower with bower-npm-resolver into our deployment of various npm assets. After initially being thrilled that this was possible we started running into the error "TypeError: Arguments to path.join must be strings" when running bower install or bower update.

I have spent the last two days researching to find the cause of this issue. I noticed the dependency issue that was occurring in Bower proper a couple years ago with tmp version 0.0.24. Although there has been no new issue in Bower that I can locate involving this issue.

I have tried downgrading the version of tmp and bower and still was able to produce the error. I downgraded from version 0.4.0 to 0.3.0 of bower-npm-resolver and the issue stopped immediately.

In order to reproduce the issue I had a bower.json with 2 deps (number of deps should not matter). No cached packages (bower cache clean) and ran bower install. What appears to be random the install will fail with the following stack and console trace.

```
Stack trace:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at ResolveCache._readPkgMeta (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/lib/core/ResolveCache.js:337:25)
    at ResolveCache.store (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/lib/core/ResolveCache.js:108:51)
    at /opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/lib/core/PackageRepository.js:188:35
    at _fulfilled (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:796:13)
    at /opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:125:13)

Console trace:
Error
    at StandardRenderer.error (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/lib/commands/index.js:68:20
    at _rejected (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /opt/nvm/versions/node/v0.12.7/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.7.0
Node version: 0.12.7
OS: Linux 2.6.32-504.el6.x86_64 x64
```

I say random occurrence because sometimes it will not fail and sometimes after fail multiple times it will work. But it only will occur when the cache is cleared.

For the time being, I have resolved this issue by reverting to the 0.3.0 version and hope this helps anyone who might also be running into this issue. My coworker who did some further debugging will probably reply with some more internal details that he saw while trying to determine the cause of this issue.

Thanks in advance.

**Comment by edg-boulder** [comment] 2016-08-04 22:00
More information regarding the above issue:

The error is occuring when ResolveCache._readPkgMeta(dir) is called with {dir} being undefined.

In the 0.3.0 version the same call has a value every time it is called.

**Comment by mjeanroy** [comment] 2016-08-05 07:17
Interesting, with v0.4.0, we changed how the package is downloaded (we use `npm pack` instead of a direct download), maybe we missed something during this change. I never saw this issue, but most of the time the cache is probably used.

Feel free to share more details while I try to reproduce it.

Thank you for your feedback!

**Comment by jakub-g** [comment] 2016-08-05 16:11
FWIW, we're using using bower-npm-resolver@0.2.0 bower@1.7.9 (latest) npm @2.15.8, on our MacOSX CI machine

Until today, with node 0.12.2 everything was working fine but when I upgraded to node 4.4.7 we got this


    ...
    bower mycompany-mypackage#5.3.x       not-cached mycompany-mypackage#5.3.x
    bower mycompany-mypackage#5.3.x          resolve mycompany-mypackage#5.3.x
    bower mycompany-mypackage#5.3.x            error Path must be a string. Received undefined

    Stack trace:
    TypeError: Path must be a string. Received undefined
        at assertPath (path.js:8:11)
        at Object.posix.join (path.js:479:5)
        at ResolveCache._readPkgMeta (/usr/local/lib/node_modules/bower/lib/core/ResolveCache.js:337:25)
        at ResolveCache.store (/usr/local/lib/node_modules/bower/lib/core/ResolveCache.js:108:51)
        at /usr/local/lib/node_modules/bower/lib/core/PackageRepository.js:190:35
        at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
        at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
        at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)

so the problem is quite similar but the circumstances different (you have old node and new resolver, i have new node and old resolver)

Will probably investigate it more next week...

**Comment by chadrobertson75** [comment] 2016-08-08 22:14
@jakub-g - I was curious if the node version might have any effect. 

@mjeanroy - This would only occur if the cache did not exist. If the cache existed it seemed to work fine.

**Comment by mjeanroy** [comment] 2016-08-29 10:30
@chadrobertson75 This issue should be fix with v0.5.0. Please, let me know if it does not work for you!

**Comment by chadrobertson75** [comment] 2016-08-29 14:51
@mjeanroy Thanks! I will let you know if I run into any issues.

**Comment by mjeanroy** [comment] 2016-09-20 08:24
@chadrobertson75 I'm closing this issue, feel free to reopen if you see the problem again.

**Closed by mjeanroy** 2016-09-20 08:24 UTC
